# Top 8 powerful unctions in python for deep data analysis

1. Groupby
2. Pivot_table
3. Aggregate
4. Cross_tab
5. Concat
6. Apply
7. Lambda
8. Del (Keyword)

## 1. Groupby

In [1]:
import pandas as pd

In [15]:
insurance_data = pd.read_csv("insurance.csv")
insurance_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

### 1.1 Perform initial analysis

In [3]:
insurance_data.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [4]:
insurance_data.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [5]:
insurance_data.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

### 1.2 Pull up the insurance charges based on region

In [7]:
insurance_data["region"].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [8]:
insurance_data["region"].nunique()

4

In [9]:
insurance_data.groupby(by = "region")["charges"].mean()

region
northeast    13406.384516
northwest    12417.575374
southeast    14735.411438
southwest    12346.937377
Name: charges, dtype: float64

In [10]:
insurance_data.groupby(by = "region")["charges"].mean().round(2)

region
northeast    13406.38
northwest    12417.58
southeast    14735.41
southwest    12346.94
Name: charges, dtype: float64

In [11]:
insurance_data.groupby(by = "region")["charges"].mean().round(2).sort_values()

region
southwest    12346.94
northwest    12417.58
northeast    13406.38
southeast    14735.41
Name: charges, dtype: float64

### 1.3 Pull up the insurance charges based on region & sex

In [12]:
insurance_data.groupby(by = ["region", "sex"])["charges"].mean().round(2).sort_values()

region     sex
southwest  female    11274.41
northwest  male      12354.12
           female    12479.87
northeast  female    12953.20
southwest  male      13412.88
southeast  female    13499.67
northeast  male      13854.01
southeast  male      15879.62
Name: charges, dtype: float64

In [21]:
insurance_data.groupby(by = ["region", "sex"])["charges"].mean().round(2).sort_values(ascending = False)

region     sex
southeast  male      15879.62
northeast  male      13854.01
southeast  female    13499.67
southwest  male      13412.88
northeast  female    12953.20
northwest  female    12479.87
           male      12354.12
southwest  female    11274.41
Name: charges, dtype: float64

## 2. Pivot_table

* Prsentable comparing 2 categorical features Vs 1 continuous

=> Continuous - countable/segmentable/has unit

=> Discrete   - countable/ no unit

In [18]:
pd.pivot_table(data = insurance_data, values = "charges", index = "region", columns = "sex").round()

sex         female     male
region
northeast  12953.0  13854.0
northwest  12480.0  12354.0
southeast  13500.0  15880.0
southwest  11274.0  13413.0

In [5]:
import pandas as pd
pd.pivot_table(data = insurance_data, values = "charges", index = "region", columns = ["sex", "children"]).round()

sex         female                                                  male  \
children         0        1        2        3        4        5        0
region
northeast   9790.0  17125.0  14523.0  13730.0  14542.0      NaN  13390.0
northwest  12584.0  11119.0  13128.0  13431.0  11024.0   8966.0   9813.0
southeast  14862.0   9870.0  11766.0  19723.0  18267.0   9924.0  13792.0
southwest  10150.0  10842.0  16230.0   8439.0  10946.0  10024.0  13727.0

sex
children         1        2        3        4        5
region
northeast  15474.0  12318.0  14935.0  14442.0   6979.0
northwest   9515.0  13763.0  22971.0  11508.0      NaN
southeast  17425.0  18648.0  17102.0   8727.0  10307.0
southwest   9971.0  18876.0  12072.0  17924.0   6865.0

## 3. Aggregate

In [6]:
insurance_data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

### 3.1 Find out the average insurance charges based on region

In [9]:
insurance_data.groupby(by = "region")["charges"].mean().round(2).sort_values(ascending = False)

region
southeast    14735.41
northeast    13406.38
northwest    12417.58
southwest    12346.94
Name: charges, dtype: float64

In [7]:
insurance_data.groupby(by = ["region", "sex"])["charges"].mean().round(2).sort_values(ascending = False)

region     sex
southeast  male      15879.62
northeast  male      13854.01
southeast  female    13499.67
southwest  male      13412.88
northeast  female    12953.20
northwest  female    12479.87
           male      12354.12
southwest  female    11274.41
Name: charges, dtype: float64

In [10]:
insurance_data.groupby(by = "region")["charges"].aggregate(func = ["mean", "min", "max", "sum"]).round()

              mean     min      max        sum
region
northeast  13406.0  1695.0  58571.0  4343669.0
northwest  12418.0  1621.0  60021.0  4035712.0
southeast  14735.0  1122.0  63770.0  5363690.0
southwest  12347.0  1242.0  52591.0  4012755.0

In [13]:
insurance_data.groupby(by = ["region", "sex"])["charges"].aggregate(func = ["mean", "min", "max", "sum"]).round()

                     mean     min      max        sum
region    sex
northeast female  12953.0  2196.0  58571.0  2085466.0
          male    13854.0  1695.0  48549.0  2258203.0
northwest female  12480.0  2117.0  55135.0  2046699.0
          male    12354.0  1621.0  60021.0  1989013.0
southeast female  13500.0  1608.0  63770.0  2362442.0
          male    15880.0  1122.0  62593.0  3001248.0
southwest female  11274.0  1728.0  48824.0  1826455.0
          male    13413.0  1242.0  52591.0  2186300.0

## 4. Cross Tab

In [14]:
insurance_data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

### 4.1 How many smokers & non smokers based on the region

In [17]:
pd.crosstab(index = insurance_data["region"], columns = insurance_data["smoker"], margins = True)

smoker       no  yes   All
region
northeast   257   67   324
northwest   267   58   325
southeast   273   91   364
southwest   267   58   325
All        1064  274  1338

In [19]:
pd.crosstab(index = insurance_data["region"], columns = insurance_data["sex"], margins = True)

sex        female  male   All
region
northeast     161   163   324
northwest     164   161   325
southeast     175   189   364
southwest     162   163   325
All           662   676  1338

## 5. Concat

In [6]:
sales_data_2017 = pd.read_csv("Sales Transcations-2017.csv")
sales_data_2018 = pd.read_csv("Sales Transcations-2018.csv")
sales_data_2019 = pd.read_csv("Sales Transcations-2019.csv")

In [10]:
sales_full_data = pd.concat(objs = [sales_data_2017, sales_data_2018, sales_data_2019])
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0,NaN,NaN,NaN
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0,NaN,NaN,NaN
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0,NaN,NaN,NaN
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0,NaN,NaN,NaN
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [11]:
sales_full_data.isna().sum()

Date                7203
Voucher             7182
Party                 25
Product             7203
Qty                 7182
Rate                7183
Gross             102744
Disc              156739
Voucher Amount    143266
dtype: int64

In [13]:
sales_full_data.dtypes

Date              object
Voucher           object
Party             object
Product           object
Qty               object
Rate              object
Gross             object
Disc              object
Voucher Amount    object
dtype: object

## 6. Apply

In [16]:
insurance_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

### 6.1 Create a new column in the same data frame with the name "Eligibility Criteria" where if age is > 20, say eligible else not

In [17]:
def get_age(x):
    if x > 20:
        return "Eligible"
    else:
        return "Not Eligible"

In [19]:
insurance_data["Eligibility Criteria"] = insurance_data["age"].apply(get_age)
insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligibility Criteria
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible

## 7. Lambda

* Also called as Anonymous Function / Nameless Function

In [21]:
insurance_data["Eligibility Criteria_2"] = insurance_data["age"].apply(lambda x:1 if x > 20 else 0)
insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligibility Criteria,Eligibility Criteria_2
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible,0
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible,0
2,28,male,33.000,3,no,southeast,4449.46200,Eligible,1
3,33,male,22.705,0,no,northwest,21984.47061,Eligible,1
4,32,male,28.880,0,no,northwest,3866.85520,Eligible,1
...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible,1
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible,0
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible,0
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible,1
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible,1

## 8. Del Keyword

In [24]:
insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligibility Criteria_2
0,19,female,27.900,0,yes,southwest,16884.92400,0
1,18,male,33.770,1,no,southeast,1725.55230,0
2,28,male,33.000,3,no,southeast,4449.46200,1
3,33,male,22.705,0,no,northwest,21984.47061,1
4,32,male,28.880,0,no,northwest,3866.85520,1
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,1
1334,18,female,31.920,0,no,northeast,2205.98080,0
1335,18,female,36.850,0,no,southeast,1629.83350,0
1336,21,female,25.800,0,no,southwest,2007.94500,1
1337,61,female,29.070,0,yes,northwest,29141.36030,1

In [26]:
del insurance_data["Eligibility Criteria_2"]
insurance_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]