# TASK 1
-> Explain built-in functions of Python data structures with examples

## List

### Append

In [7]:
student_marks = [89, 85, 75, 65, 98]
student_marks.append(95)
student_marks

[89, 85, 75, 65, 98, 95]

### Clear

In [8]:
items_to_buy = ['orange', 'carrot', 'milk', 'onion', 'garlic']
items_to_buy.clear()
items_to_buy

[]

### Copy

In [13]:
random = [1.432, 234, 'number', 'alphabets']
random_2 = random.copy()
print(random)
print(random_2)

[1.432, 234, 'number', 'alphabets']
[1.432, 234, 'number', 'alphabets']

### Count

In [19]:
items = ['Apple', 'Banana', 'Grapes', 'Orange', 'Apple', 4.58, 184]
items.count('Apple')

2

### Extend

In [24]:
items = ['Apple', 'Banana', 'Grapes', 'Orange', 'Apple']
items_2 = [4.58, 184]
items.extend(items_2)
print(items)

['Apple', 'Banana', 'Grapes', 'Orange', 'Apple', 4.58, 184]

### Index

In [25]:
items = ['Apple', 'Banana', 'Grapes', 'Orange', 'Apple', 4.58, 184]
items.index('Grapes')

2

### Insert

In [31]:
items = ['Apple', 'Banana', 'Grapes', 'Orange', 'Apple', 4.58, 184]
items.insert(1, 'Cherry')
items

['Apple', 'Cherry', 'Banana', 'Grapes', 'Orange', 'Apple', 4.58, 184]

### Pop

In [35]:
items = ['Apple', 'Banana', 'Grapes', 'Orange', 'Apple', 4.58, 184]
items.pop(4)

'Apple'

### Remove

In [40]:
items = ['Apple', 'Banana', 'Grapes', 'Orange', 'Apple', 4.58, 184]
items.remove('Grapes')
items

['Apple', 'Banana', 'Orange', 'Apple', 4.58, 184]

### Reverse

In [45]:
items = [12, 10.5, 20, 15, 10]
items.reverse()
items

[10, 15, 20, 10.5, 12]

### Sort

In [46]:
items = [12, 10.5, 20, 15, 10]
items.sort()
items

[10, 10.5, 12, 15, 20]

## Set

### Add

In [65]:
items = {'Apple', 'Banana', 'Grapes', 'Orange', 'Apple', 4.58, 184}
items.add('55')
items

{184, 4.58, '55', 'Apple', 'Banana', 'Grapes', 'Orange'}

### Clear

In [63]:
items = {'Apple', 'Banana', 'Grapes', 'Orange', 'Apple', 4.58, 184}
items.clear()
items

set()

### Copy

In [60]:
items = {'Apple', 'Banana', 'Grapes', 'Orange', 'Apple', 4.58, 184}
items_2 = items.copy()
print(items)
print(items_2)

{'Apple', 4.58, 'Grapes', 184, 'Orange', 'Banana'}
{'Apple', 4.58, 'Grapes', 184, 'Orange', 'Banana'}

### Difference

In [82]:
items = {10, 20, 30}
items_2 = {15, 20, 30, 50}
print(items.difference(items_2))
print(items)

{10}
{10, 20, 30}

### Difference Update

In [84]:
items = {5, 10, 15, 20, 30}
items_2 = {20, 30, 50}
items.difference_update(items_2)
print(items)

{5, 10, 15}

### Discard

In [95]:
items = {'Apple', 'Banana', 'Grapes', 'Orange', 'Apple', 4.58, 184}
items.discard(184)
items

{4.58, 'Apple', 'Banana', 'Grapes', 'Orange'}

### Intersection

In [101]:
items = {10, 20, 30}
items_2 = {15, 20, 30, 50}
items_3 = {25,30}
print(items.intersection(items_2,items_3))

{30}

### Intersection_Update

In [103]:
items = {10, 20, 30}
items_2 = {15, 20, 30, 50}
items.intersection_update(items_2)
print(items)

{20, 30}

### Isdisjoint

In [107]:
items = {10, 20, 30}
items_2 = {15, 25, 33}
print(items.isdisjoint(items_2))

True

### Issubset

In [108]:
items = {10, 20, 30}
items_2 = {15, 20, 30, 50}
print(items.issubset(items_2))

False

In [109]:
items = {20, 30}
items_2 = {15, 20, 30, 50}
print(items.issubset(items_2))

True

### Issuperset

In [112]:
items = {10, 20, 30}
items_2 = {15, 20, 30, 50}
print(items.issuperset(items_2))

False

In [116]:
items = {10, 15, 20, 30, 50}
items_2 = {15, 20, 30, 50}
print(items.issuperset(items_2))

True

### Pop

In [125]:
items = {10, 20, 30}
x = items.pop()
print(x)

10

### Remove

In [127]:
items = {10, 20, 30}
items.remove(10)
items

{20, 30}

### Symmetric Difference

In [132]:
items = {10, 20, 30}
items_2 = {10, 15, 20, 30, 50}
print(items.symmetric_difference(items_2))

{50, 15}

### Symmetric Difference Update

In [138]:
items = {10, 20, 30}
items_2 = {20, 30, 40}
items.symmetric_difference_update(items_2)
print(items)

{40, 10}

### Union

In [141]:
items = {10, 20, 30}
items_2 = {20, 30, 40}
print(items.union(items_2))
print(items)

{20, 40, 10, 30}
{10, 20, 30}

### Update

In [143]:
items = {10, 15, 20, 30}
items_2 = {20, 30, 40}
print(items.union(items_2))
print(items)

{20, 40, 10, 30, 15}
{10, 20, 30, 15}

## Tuple

### Count

In [144]:
items = ('orange', 'carrot', 'milk', 'onion', 'garlic')
items.count('orange')

1

### Index

In [146]:
items = ('orange', 'carrot', 'milk', 'onion', 'garlic')
items.index('milk')

2

## Dictionary

### Clear

In [147]:
items = {'orange':3, 'carrot':2, 'milk':3, 'onion':2.5, 'garlic':1}
items.clear()
items

{}

### Copy

In [149]:
items = {'orange':3, 'carrot':2, 'milk':3, 'onion':2.5, 'garlic':1}
a = items.copy()
print(a)

{'orange': 3, 'carrot': 2, 'milk': 3, 'onion': 2.5, 'garlic': 1}

### Fromkeys

In [154]:
items = dict.fromkeys(['orange', 'carrot', 'milk', 'onion', 'garlic'], 1)
items

{'orange': 1, 'carrot': 1, 'milk': 1, 'onion': 1, 'garlic': 1}

### Get

In [155]:
items = {'orange':3, 'carrot':2, 'milk':3, 'onion':2.5, 'garlic':1}
a = items.get('orange')
print(a)

3

### Items

In [157]:
items = {'orange':3, 'carrot':2, 'milk':3, 'onion':2.5, 'garlic':1}
a = items.items()
print(a)

dict_items([('orange', 3), ('carrot', 2), ('milk', 3), ('onion', 2.5), ('garlic', 1)])

### Keys

In [158]:
items = {'orange':3, 'carrot':2, 'milk':3, 'onion':2.5, 'garlic':1}
a = items.keys()
print(a)

dict_keys(['orange', 'carrot', 'milk', 'onion', 'garlic'])

### Pop

In [159]:
items = {'orange':3, 'carrot':2, 'milk':3, 'onion':2.5, 'garlic':1}
items.pop('orange')
items

{'carrot': 2, 'milk': 3, 'onion': 2.5, 'garlic': 1}

### Popitem

In [164]:
items = {'orange':3, 'carrot':2, 'milk':3, 'onion':2.5, 'garlic':1}
a = items.popitem()
print(a)
items

('garlic', 1)

{'orange': 3, 'carrot': 2, 'milk': 3, 'onion': 2.5}

### Setdefault

In [172]:
items = {'orange':3, 'carrot':2, 'milk':3, 'onion':2.5, 'garlic':1}
a = items.setdefault('apple', 5)
print(items)

{'orange': 3, 'carrot': 2, 'milk': 3, 'onion': 2.5, 'garlic': 1, 'apple': 5}

### Update

In [177]:
items = {'orange':3, 'carrot':2, 'milk':3, 'onion':2.5, 'garlic':1}
a = items.update({'apple':5})
print(items)

{'orange': 3, 'carrot': 2, 'milk': 3, 'onion': 2.5, 'garlic': 1, 'apple': 5}

### Values

In [179]:
items = {'orange':3, 'carrot':2, 'milk':3, 'onion':2.5, 'garlic':1}
a = items.values()
print(a)

dict_values([3, 2, 3, 2.5, 1])

# TASK 2

-> Create 3 dataframes using dictionaries

## DataFrame 1

In [40]:
stock_details = { 'stocks_name': ['pen', 'note', 'chart paper'], 'price': [10, 45, 10], 'stock': [100, 150, 60]}
pd.DataFrame(data=stock_details)

   stocks_name  price  stock
0          pen     10    100
1         note     45    150
2  chart paper     10     60

## DataFrame 2

In [41]:
students_data = {"Name": ['Aishwariya', 'Aravind', 'Bala', 'Cynthiya', 'Jeeva', 'Ramya', 'Santhiya', 'Yamini'], 
                 "Parent_Name": ['Rajesh', 'Surya', 'Dhinesh', 'Selvakumar', 'Prakash', 'Sivakumar', 'Prahbu', 'Dhinakar'],
                 "Ph_Number": [1234567890, 2345678901, 3456789012, 4567890123, 5678901234, 6789012345, 7890123456, 8901234567]}
pd.DataFrame(data=students_data)

         Name Parent_Name   Ph_Number
0  Aishwariya      Rajesh  1234567890
1     Aravind       Surya  2345678901
2        Bala     Dhinesh  3456789012
3    Cynthiya  Selvakumar  4567890123
4       Jeeva     Prakash  5678901234
5       Ramya   Sivakumar  6789012345
6    Santhiya      Prahbu  7890123456
7      Yamini    Dhinakar  8901234567

## DataFrame 3

In [38]:
Client_Data = { 'Client_Name': ['Dhivya', 'Varsha', 'Nithish', 'Manikandan', 'Aakash', 'Andrew', 'Jegan'], 
                'Client_Place': ['Chennai', 'Chennai', 'Tirunelveli', 'Salem', 'Tuticorin', 'Kannyakumari', 'Thanjavur'],
                'Work_Status': ['Processing', 'Completed', 'Processing', 'Processing', 'Completed', 'Completed', 'Processing']}
pd.DataFrame(data = Client_Data)

  Client_Name  Client_Place Work_Status
0      Dhivya       Chennai  Processing
1      Varsha       Chennai   Completed
2     Nithish   Tirunelveli  Processing
3  Manikandan         Salem  Processing
4      Aakash     Tuticorin   Completed
5      Andrew  Kannyakumari   Completed
6       Jegan     Thanjavur  Processing