# TASK 1

In [1]:
import pandas as pd

In [2]:
sales_data_2017 = pd.read_csv("Sales Transcations-2017.csv")
sales_data_2018 = pd.read_csv("Sales Transcations-2018.csv")
sales_data_2019 = pd.read_csv("Sales Transcations-2019.csv")

In [3]:
sales_full_data = pd.concat([sales_data_2017, sales_data_2018, sales_data_2019])
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0,NaN,NaN,NaN
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0,NaN,NaN,NaN
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0,NaN,NaN,NaN
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0,NaN,NaN,NaN
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

### Performing initial analysis

In [4]:
sales_full_data.dtypes

Date              object
Voucher           object
Party             object
Product           object
Qty               object
Rate              object
Gross             object
Disc              object
Voucher Amount    object
dtype: object

In [5]:
sales_full_data.isna().sum()

Date                7203
Voucher             7182
Party                 25
Product             7203
Qty                 7182
Rate                7183
Gross             102744
Disc              156739
Voucher Amount    143266
dtype: int64

In [6]:
sales_full_data.shape

(159478, 9)

In [7]:
sales_full_data.describe()

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
count,152275,152296,159453,152275,152296,152295.0,56734,2739,16212
unique,1138,19640,1615,962,808,1905.0,2056,268,5214
top,,,TP13,14 GREEN,100,26.0,,,
freq,1708,1708,20449,3626,12529,2733.0,1708,1708,1708

### Lets check for duplicated data

In [8]:
sales_full_data.duplicated().sum()

np.int64(8520)

In [9]:
sales_full_data[sales_full_data.duplicated()].head(10)

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
411,1/8/2017,3841,TP13,PP,5,135.0,NaN,NaN,NaN
1080,2/6/2017,2099,TP13,9*12 STAR-DCUT,5,100.0,NaN,NaN,NaN
2171,3/5/2017,1122,TP13,CLASSIC 250ML,100,23.0,NaN,NaN,NaN
2176,3/5/2017,1122,TP13,CLASSIC 250ML,100,23.0,NaN,NaN,NaN
2331,3/6/2017,2107,TP13,CLASSIC 300ML,100,24.5,NaN,NaN,NaN
2618,3/11/2017,6497,TP13,CLASSIC ENJOY(750),1,1320.0,NaN,NaN,NaN
3760,4/12/2017,7398,TP13,TIRUMALA-50B(10*12),300,7.7,NaN,NaN,NaN
4303,4/17/2017,443,SHAIK SIFULLA,CYCLE-BK-13*16,10,13.0,NaN,NaN,NaN
4420,4/17/2017,552,TP13,VISHNU 300ML,100,27.5,NaN,NaN,NaN
4471,4/18/2017,497,LAKSHMIFANCY,"TAPE ROLL 2"" 50MTRS",4,125.0,NaN,NaN,NaN

In [10]:
sales_full_data = sales_full_data.drop_duplicates()

In [11]:
sales_full_data.duplicated().sum()

np.int64(0)

### Lets converts Qty & Rate from object to numeric

In [54]:
sales_full_data.loc[:, 'Qty'] = sales_full_data['Qty'].astype(int)
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-04-01,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0,3380.0,0.0,41116.0
1,2017-04-01,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0,9720.0,0.0,41116.0
2,2017-04-01,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0,11500.0,0.0,38560.0
3,2017-04-01,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0,9720.0,0.0,38560.0
4,2017-04-01,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0,8450.0,0.0,38560.0
...,...,...,...,...,...,...,...,...,...
19167,2019-10-10,Sal:4935,K.SRIHARI,16*20(100-W),140,26.0,3640.0,0.0,27000.0
19168,2019-10-10,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,5040.0,0.0,27000.0
19169,2019-10-10,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0,5120.0,0.0,27000.0
19170,2019-10-10,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,6800.0,0.0,27000.0
19171,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16.0,6400.0,0.0,27000.0

In [55]:
sales_full_data.loc[:, "Qty"] = pd.to_numeric(sales_full_data["Qty"], errors = 'coerce')
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-04-01,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0,3380.0,0.0,41116.0
1,2017-04-01,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0,9720.0,0.0,41116.0
2,2017-04-01,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0,11500.0,0.0,38560.0
3,2017-04-01,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0,9720.0,0.0,38560.0
4,2017-04-01,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0,8450.0,0.0,38560.0
...,...,...,...,...,...,...,...,...,...
19167,2019-10-10,Sal:4935,K.SRIHARI,16*20(100-W),140,26.0,3640.0,0.0,27000.0
19168,2019-10-10,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,5040.0,0.0,27000.0
19169,2019-10-10,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0,5120.0,0.0,27000.0
19170,2019-10-10,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,6800.0,0.0,27000.0
19171,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16.0,6400.0,0.0,27000.0

In [56]:
sales_full_data.loc[:, 'Rate'] = pd.to_numeric(sales_full_data["Rate"], errors = 'coerce')
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-04-01,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0,3380.0,0.0,41116.0
1,2017-04-01,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0,9720.0,0.0,41116.0
2,2017-04-01,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0,11500.0,0.0,38560.0
3,2017-04-01,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0,9720.0,0.0,38560.0
4,2017-04-01,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0,8450.0,0.0,38560.0
...,...,...,...,...,...,...,...,...,...
19167,2019-10-10,Sal:4935,K.SRIHARI,16*20(100-W),140,26.0,3640.0,0.0,27000.0
19168,2019-10-10,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,5040.0,0.0,27000.0
19169,2019-10-10,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0,5120.0,0.0,27000.0
19170,2019-10-10,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,6800.0,0.0,27000.0
19171,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16.0,6400.0,0.0,27000.0

In [18]:
sales_full_data.dtypes

Date               object
Voucher            object
Party              object
Product            object
Qty               float64
Rate              float64
Gross              object
Disc               object
Voucher Amount     object
dtype: object

### Lets calculate the gross

In [57]:
sales_full_data.loc[:, "Gross"] = sales_full_data["Qty"] * sales_full_data["Rate"]
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-04-01,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0,3380.0,0.0,41116.0
1,2017-04-01,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0,9720.0,0.0,41116.0
2,2017-04-01,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0,11500.0,0.0,38560.0
3,2017-04-01,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0,9720.0,0.0,38560.0
4,2017-04-01,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0,8450.0,0.0,38560.0
...,...,...,...,...,...,...,...,...,...
19167,2019-10-10,Sal:4935,K.SRIHARI,16*20(100-W),140,26.0,3640.0,0.0,27000.0
19168,2019-10-10,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,5040.0,0.0,27000.0
19169,2019-10-10,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0,5120.0,0.0,27000.0
19170,2019-10-10,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,6800.0,0.0,27000.0
19171,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16.0,6400.0,0.0,27000.0

In [59]:
sales_full_data.dtypes

Date              datetime64[ns]
Voucher                   object
Party                     object
Product                   object
Qty                        int64
Rate                     float64
Gross                    float64
Disc                     float64
Voucher Amount           float64
dtype: object

### Performing to_datatime

In [60]:
sales_full_data.loc[:, 'Date'] = pd.to_datetime(sales_full_data['Date'], dayfirst=True, errors='coerce')
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-04-01,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0,3380.0,0.0,41116.0
1,2017-04-01,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0,9720.0,0.0,41116.0
2,2017-04-01,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0,11500.0,0.0,38560.0
3,2017-04-01,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0,9720.0,0.0,38560.0
4,2017-04-01,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0,8450.0,0.0,38560.0
...,...,...,...,...,...,...,...,...,...
19167,2019-10-10,Sal:4935,K.SRIHARI,16*20(100-W),140,26.0,3640.0,0.0,27000.0
19168,2019-10-10,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,5040.0,0.0,27000.0
19169,2019-10-10,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0,5120.0,0.0,27000.0
19170,2019-10-10,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,6800.0,0.0,27000.0
19171,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16.0,6400.0,0.0,27000.0

In [61]:
sales_full_data.dtypes

Date              datetime64[ns]
Voucher                   object
Party                     object
Product                   object
Qty                        int64
Rate                     float64
Gross                    float64
Disc                     float64
Voucher Amount           float64
dtype: object

### Lets remove the missing datas

In [62]:
sales_full_data = sales_full_data.dropna(subset = ['Qty'])
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-04-01,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0,3380.0,0.0,41116.0
1,2017-04-01,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0,9720.0,0.0,41116.0
2,2017-04-01,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0,11500.0,0.0,38560.0
3,2017-04-01,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0,9720.0,0.0,38560.0
4,2017-04-01,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0,8450.0,0.0,38560.0
...,...,...,...,...,...,...,...,...,...
19167,2019-10-10,Sal:4935,K.SRIHARI,16*20(100-W),140,26.0,3640.0,0.0,27000.0
19168,2019-10-10,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,5040.0,0.0,27000.0
19169,2019-10-10,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0,5120.0,0.0,27000.0
19170,2019-10-10,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,6800.0,0.0,27000.0
19171,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16.0,6400.0,0.0,27000.0

In [63]:
sales_full_data = sales_full_data.dropna(subset=['Date'])
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-04-01,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0,3380.0,0.0,41116.0
1,2017-04-01,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0,9720.0,0.0,41116.0
2,2017-04-01,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0,11500.0,0.0,38560.0
3,2017-04-01,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0,9720.0,0.0,38560.0
4,2017-04-01,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0,8450.0,0.0,38560.0
...,...,...,...,...,...,...,...,...,...
19167,2019-10-10,Sal:4935,K.SRIHARI,16*20(100-W),140,26.0,3640.0,0.0,27000.0
19168,2019-10-10,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,5040.0,0.0,27000.0
19169,2019-10-10,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0,5120.0,0.0,27000.0
19170,2019-10-10,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,6800.0,0.0,27000.0
19171,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16.0,6400.0,0.0,27000.0

In [64]:
sales_full_data = sales_full_data.dropna(subset=['Rate'])
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-04-01,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0,3380.0,0.0,41116.0
1,2017-04-01,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0,9720.0,0.0,41116.0
2,2017-04-01,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0,11500.0,0.0,38560.0
3,2017-04-01,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0,9720.0,0.0,38560.0
4,2017-04-01,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0,8450.0,0.0,38560.0
...,...,...,...,...,...,...,...,...,...
19167,2019-10-10,Sal:4935,K.SRIHARI,16*20(100-W),140,26.0,3640.0,0.0,27000.0
19168,2019-10-10,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,5040.0,0.0,27000.0
19169,2019-10-10,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0,5120.0,0.0,27000.0
19170,2019-10-10,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,6800.0,0.0,27000.0
19171,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16.0,6400.0,0.0,27000.0

### Lets clean the discount

In [65]:
sales_full_data.loc[:, 'Disc'] = sales_full_data['Disc'].fillna(0)
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-04-01,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0,3380.0,0.0,41116.0
1,2017-04-01,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0,9720.0,0.0,41116.0
2,2017-04-01,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0,11500.0,0.0,38560.0
3,2017-04-01,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0,9720.0,0.0,38560.0
4,2017-04-01,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0,8450.0,0.0,38560.0
...,...,...,...,...,...,...,...,...,...
19167,2019-10-10,Sal:4935,K.SRIHARI,16*20(100-W),140,26.0,3640.0,0.0,27000.0
19168,2019-10-10,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,5040.0,0.0,27000.0
19169,2019-10-10,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0,5120.0,0.0,27000.0
19170,2019-10-10,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,6800.0,0.0,27000.0
19171,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16.0,6400.0,0.0,27000.0

In [66]:
sales_full_data.loc[:, 'Disc'] = pd.to_numeric(sales_full_data['Disc'], errors='coerce')
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-04-01,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0,3380.0,0.0,41116.0
1,2017-04-01,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0,9720.0,0.0,41116.0
2,2017-04-01,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0,11500.0,0.0,38560.0
3,2017-04-01,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0,9720.0,0.0,38560.0
4,2017-04-01,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0,8450.0,0.0,38560.0
...,...,...,...,...,...,...,...,...,...
19167,2019-10-10,Sal:4935,K.SRIHARI,16*20(100-W),140,26.0,3640.0,0.0,27000.0
19168,2019-10-10,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,5040.0,0.0,27000.0
19169,2019-10-10,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0,5120.0,0.0,27000.0
19170,2019-10-10,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,6800.0,0.0,27000.0
19171,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16.0,6400.0,0.0,27000.0

### Lets check voucher

In [67]:
sales_full_data.loc[:, 'Voucher Amount'] = (sales_full_data.groupby('Voucher')['Gross'].transform('sum'))
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-04-01,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0,3380.0,0.0,41116.0
1,2017-04-01,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0,9720.0,0.0,41116.0
2,2017-04-01,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0,11500.0,0.0,38560.0
3,2017-04-01,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0,9720.0,0.0,38560.0
4,2017-04-01,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0,8450.0,0.0,38560.0
...,...,...,...,...,...,...,...,...,...
19167,2019-10-10,Sal:4935,K.SRIHARI,16*20(100-W),140,26.0,3640.0,0.0,27000.0
19168,2019-10-10,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,5040.0,0.0,27000.0
19169,2019-10-10,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0,5120.0,0.0,27000.0
19170,2019-10-10,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,6800.0,0.0,27000.0
19171,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16.0,6400.0,0.0,27000.0

### Final Check

In [68]:
sales_full_data.isna().sum()

Date              0
Voucher           0
Party             0
Product           0
Qty               0
Rate              0
Gross             0
Disc              0
Voucher Amount    0
dtype: int64

In [69]:
sales_full_data.dtypes

Date              datetime64[ns]
Voucher                   object
Party                     object
Product                   object
Qty                        int64
Rate                     float64
Gross                    float64
Disc                     float64
Voucher Amount           float64
dtype: object

In [73]:
sales_full_data.describe()

,Date,Qty,Rate,Gross,Disc,Voucher Amount
count,87343,87343.000000,87343.000000,87343.000000,87343.000000,87343.000000
mean,2018-09-26 11:59:12.023630848,142.567166,152.552306,2808.836940,2.590293,25854.203628
min,2017-04-01 00:00:00,0.000000,0.010000,0.000000,0.000000,100.000000
25%,2018-05-08 00:00:00,10.000000,16.000000,775.000000,0.000000,9600.000000
50%,2018-10-10 00:00:00,50.000000,28.000000,2200.000000,0.000000,17625.000000
75%,2019-04-03 00:00:00,140.000000,130.000000,3400.000000,0.000000,32755.000000
max,2019-10-10 00:00:00,35000.000000,200000.000000,200000.000000,990.000000,288300.000000
std,NaN,490.484415,1455.582246,3660.440826,35.525015,25524.018007

# TASK 2

* Merge Function

In [79]:
import pandas as pd

data1 = { "Product_ID": [1, 2, 3], "Product_Name": ["Pen", "Pencil", "Book"] }

data1 = pd.DataFrame(data1)
data1

   Product_ID Product_Name
0           1          Pen
1           2       Pencil
2           3         Book

In [90]:
data2 = { "Product_ID": [1, 2, 4], "Price": [10, 5, 100] }

data2 = pd.DataFrame(data2)
data2

   Product_ID  Price
0           1     10
1           2      5
2           4    100

## Inner

In [91]:
pd.merge(data1, data2, on='Product_ID', how='inner')

   Product_ID Product_Name  Price
0           1          Pen     10
1           2       Pencil      5

## Left

In [92]:
pd.merge(data1, data2, on='Product_ID', how='left')

   Product_ID Product_Name  Price
0           1          Pen   10.0
1           2       Pencil    5.0
2           3         Book    NaN

## Right

In [93]:
pd.merge(data1, data2, on='Product_ID', how='right')

   Product_ID Product_Name  Price
0           1          Pen     10
1           2       Pencil      5
2           4          NaN    100

## Outer

In [94]:
pd.merge(data1, data2, on='Product_ID', how='outer')

   Product_ID Product_Name  Price
0           1          Pen   10.0
1           2       Pencil    5.0
2           3         Book    NaN
3           4          NaN  100.0

# TASK 3

* List Comprehension

In [95]:
numbers = [x**2 for x in range(6)]

print(numbers)

[0, 1, 4, 9, 16, 25]

In [96]:
even_numbers = [x for x in range(1,11) if x % 2 == 0]

print(even_numbers)

[2, 4, 6, 8, 10]

# Task 4

* Lambda Function

## Map

In [97]:
numbers = [1, 2, 3, 4]

result = list(map(lambda x: x**2, numbers))

print(result)

[1, 4, 9, 16]

## Filter

In [98]:
numbers = [1,2,3,4,5,6]

result = list(filter(lambda x: x % 2 == 0, numbers))

print(result)

[2, 4, 6]

## Reduce

In [100]:
from functools import reduce

numbers = [1,2,3,4]

result = reduce(lambda x, y: x + y, numbers)

print(result)

10